# Generated by Django 4.2.7 on 2026-10-02 18:47

import admin_control.crypto
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=11)),
                ('channels_id', models.JSONField(default=list)),
                ('status', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sms_campaign_manager_campaign',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sms_campaign_manager_channel',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalTPSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('global_tps', models.PositiveIntegerField(default=4000)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sms_campaign_manager_globaltpsconfig',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NAddressesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('max_addresses_per_request', models.PositiveIntegerField(default=1000)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sms_campaign_manager_naddressesconfig',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SenderID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sms_campaign_manager_senderid',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SMSCConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('base_url', models.URLField(max_length=500)),
                ('send_endpoint', models.CharField(default='/api/send', max_length=255)),
                ('http_method', models.CharField(default='POST', max_length=10)),
                ('auth_type', models.CharField(default='api_key', max_length=20)),
                ('api_key', admin_control.crypto.SharedEncryptedCharField(blank=True, default='', max_length=500)),
                ('api_secret', admin_control.crypto.SharedEncryptedCharField(blank=True, default='', max_length=500)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', admin_control.crypto.SharedEncryptedCharField(blank=True, default='', max_length=500)),
                ('extra_headers', models.JSONField(blank=True, default=dict)),
                ('extra_params', models.JSONField(blank=True, default=dict)),
                ('rate_limit_per_second', models.PositiveIntegerField(default=100)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=3000)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('retry_backoff_seconds', models.PositiveIntegerField(default=5)),
                ('max_addresses_per_request', models.PositiveIntegerField(default=1000)),
                ('request_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('connect_timeout_seconds', models.PositiveIntegerField(default=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_test_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sms_campaign_manager_smscconfig',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CAMPAIGN_MANAGER', 'Campaign Manager')], db_index=True, default='CAMPAIGN_MANAGER', max_length=24)),
                ('department', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_locked', models.BooleanField(default=False)),
                ('tps_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channels', models.ManyToManyField(blank=True, related_name='assigned_profiles', to='admin_control.channel')),
                ('n_address_configs', models.ManyToManyField(blank=True, related_name='assigned_profiles', to='admin_control.naddressesconfig')),
                ('sender_ids', models.ManyToManyField(blank=True, related_name='assigned_profiles', to='admin_control.senderid')),
                ('sms_configs', models.ManyToManyField(blank=True, related_name='assigned_profiles', to='admin_control.smscconfig')),
                ('tps_configs', models.ManyToManyField(blank=True, related_name='assigned_profiles', to='admin_control.globaltpsconfig')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='SenderSMSCBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_control.senderid')),
                ('smsc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_control.smscconfig')),
            ],
        ),
        migrations.CreateModel(
            name='NAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
                ('address_type', models.CharField(choices=[('MSISDN', 'MSISDN'), ('ALPHANUMERIC', 'Alphanumeric'), ('POOL', 'Pool')], max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tps_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_n_addresses', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='n_addresses', to='admin_control.channel')),
                ('sender_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='n_addresses', to='admin_control.senderid')),
                ('smsc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='n_addresses', to='admin_control.smscconfig')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=254)),
                ('succeeded', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChannelSMSCBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tps', models.PositiveIntegerField(default=100)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('allowed_sender_ids', models.ManyToManyField(blank=True, to='admin_control.senderid')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_control.channel')),
                ('smsc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_control.smscconfig')),
            ],
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('object_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='sendersmscbinding',
            constraint=models.UniqueConstraint(fields=('sender_id', 'smsc'), name='admin_sender_smsc_unique'),
        ),
        migrations.AddConstraint(
            model_name='channelsmscbinding',
            constraint=models.UniqueConstraint(fields=('channel', 'smsc'), name='admin_channel_smsc_unique'),
        ),
    ]
