# Generated by Django 4.2.7 on 2026-10-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0002_backfill_user_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
