# Generated by Django 4.2.7 on 2026-10-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0003_alter_userprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderIDDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('ALPHANUMERIC', 'Alphanumeric'), ('NUMERIC', 'Numeric'), ('SHORT_CODE', 'Short code')], default='ALPHANUMERIC', max_length=16)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('tps_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_details', to='admin_control.senderid')),
            ],
        ),
    ]
