/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as KafkaMonitorRouteImport } from './routes/kafka-monitor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NAddressesRouteImport } from './routes/n-addresses'
import { Route as SenderIdsRouteImport } from './routes/sender-ids'
import { Route as SmscAccountsRouteImport } from './routes/smsc-accounts'
import { Route as SmtpRouteImport } from './routes/smtp'
import { Route as SystemLogsRouteImport } from './routes/system-logs'
import { Route as TpsRouteImport } from './routes/tps'
import { Route as TpsNAddressesRouteImport } from './routes/tps-n-addresses'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const KafkaMonitorRoute = KafkaMonitorRouteImport.update({
  id: '/kafka-monitor',
  path: '/kafka-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NAddressesRoute = NAddressesRouteImport.update({
  id: '/n-addresses',
  path: '/n-addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const SenderIdsRoute = SenderIdsRouteImport.update({
  id: '/sender-ids',
  path: '/sender-ids',
  getParentRoute: () => rootRouteImport,
} as any)
const SmscAccountsRoute = SmscAccountsRouteImport.update({
  id: '/smsc-accounts',
  path: '/smsc-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SmtpRoute = SmtpRouteImport.update({
  id: '/smtp',
  path: '/smtp',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemLogsRoute = SystemLogsRouteImport.update({
  id: '/system-logs',
  path: '/system-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const TpsRoute = TpsRouteImport.update({
  id: '/tps',
  path: '/tps',
  getParentRoute: () => rootRouteImport,
} as any)
const TpsNAddressesRoute = TpsNAddressesRouteImport.update({
  id: '/tps-n-addresses',
  path: '/tps-n-addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/channels': typeof ChannelsRoute
  '/kafka-monitor': typeof KafkaMonitorRoute
  '/login': typeof LoginRoute
  '/n-addresses': typeof NAddressesRoute
  '/sender-ids': typeof SenderIdsRoute
  '/smsc-accounts': typeof SmscAccountsRoute
  '/smtp': typeof SmtpRoute
  '/system-logs': typeof SystemLogsRoute
  '/tps': typeof TpsRoute
  '/tps-n-addresses': typeof TpsNAddressesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/channels': typeof ChannelsRoute
  '/kafka-monitor': typeof KafkaMonitorRoute
  '/login': typeof LoginRoute
  '/n-addresses': typeof NAddressesRoute
  '/sender-ids': typeof SenderIdsRoute
  '/smsc-accounts': typeof SmscAccountsRoute
  '/smtp': typeof SmtpRoute
  '/system-logs': typeof SystemLogsRoute
  '/tps': typeof TpsRoute
  '/tps-n-addresses': typeof TpsNAddressesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/channels': typeof ChannelsRoute
  '/kafka-monitor': typeof KafkaMonitorRoute
  '/login': typeof LoginRoute
  '/n-addresses': typeof NAddressesRoute
  '/sender-ids': typeof SenderIdsRoute
  '/smsc-accounts': typeof SmscAccountsRoute
  '/smtp': typeof SmtpRoute
  '/system-logs': typeof SystemLogsRoute
  '/tps': typeof TpsRoute
  '/tps-n-addresses': typeof TpsNAddressesRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/channels'
    | '/kafka-monitor'
    | '/login'
    | '/n-addresses'
    | '/sender-ids'
    | '/smsc-accounts'
    | '/smtp'
    | '/system-logs'
    | '/tps'
    | '/tps-n-addresses'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/channels'
    | '/kafka-monitor'
    | '/login'
    | '/n-addresses'
    | '/sender-ids'
    | '/smsc-accounts'
    | '/smtp'
    | '/system-logs'
    | '/tps'
    | '/tps-n-addresses'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/channels'
    | '/kafka-monitor'
    | '/login'
    | '/n-addresses'
    | '/sender-ids'
    | '/smsc-accounts'
    | '/smtp'
    | '/system-logs'
    | '/tps'
    | '/tps-n-addresses'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRoute
  ChannelsRoute: typeof ChannelsRoute
  KafkaMonitorRoute: typeof KafkaMonitorRoute
  LoginRoute: typeof LoginRoute
  NAddressesRoute: typeof NAddressesRoute
  SenderIdsRoute: typeof SenderIdsRoute
  SmscAccountsRoute: typeof SmscAccountsRoute
  SmtpRoute: typeof SmtpRoute
  SystemLogsRoute: typeof SystemLogsRoute
  TpsRoute: typeof TpsRoute
  TpsNAddressesRoute: typeof TpsNAddressesRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kafka-monitor': {
      id: '/kafka-monitor'
      path: '/kafka-monitor'
      fullPath: '/kafka-monitor'
      preLoaderRoute: typeof KafkaMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n-addresses': {
      id: '/n-addresses'
      path: '/n-addresses'
      fullPath: '/n-addresses'
      preLoaderRoute: typeof NAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sender-ids': {
      id: '/sender-ids'
      path: '/sender-ids'
      fullPath: '/sender-ids'
      preLoaderRoute: typeof SenderIdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smsc-accounts': {
      id: '/smsc-accounts'
      path: '/smsc-accounts'
      fullPath: '/smsc-accounts'
      preLoaderRoute: typeof SmscAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smtp': {
      id: '/smtp'
      path: '/smtp'
      fullPath: '/smtp'
      preLoaderRoute: typeof SmtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-logs': {
      id: '/system-logs'
      path: '/system-logs'
      fullPath: '/system-logs'
      preLoaderRoute: typeof SystemLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tps': {
      id: '/tps'
      path: '/tps'
      fullPath: '/tps'
      preLoaderRoute: typeof TpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tps-n-addresses': {
      id: '/tps-n-addresses'
      path: '/tps-n-addresses'
      fullPath: '/tps-n-addresses'
      preLoaderRoute: typeof TpsNAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRoute,
  ChannelsRoute: ChannelsRoute,
  KafkaMonitorRoute: KafkaMonitorRoute,
  LoginRoute: LoginRoute,
  NAddressesRoute: NAddressesRoute,
  SenderIdsRoute: SenderIdsRoute,
  SmscAccountsRoute: SmscAccountsRoute,
  SmtpRoute: SmtpRoute,
  SystemLogsRoute: SystemLogsRoute,
  TpsRoute: TpsRoute,
  TpsNAddressesRoute: TpsNAddressesRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
