from django.urls import path

from .views import (
	CampaignDetailView,
	CampaignHardDeleteView,
	CampaignListCreateView,
	ChannelDetailView,
	ChannelListCreateView,
	LanguageDetailView,
	LanguageListCreateView,
	MessageContentDetailView,
	MessageLanguageListView,
	ScheduleDetailView,
	ScheduleUpcomingView,
	DeliveryRecordBulkCreateView,
	DeliveryRecordBulkUpdateView,
	DeliveryRecordDetailView,
	DeliveryRecordListCreateView,
	DeliveryReportCallbackView,
	SentRecordListCreateView,
	SentRecordDetailView,
	SentRecordBulkCreateView,
	SentRecordBulkUpdateView,
	CampaignSentRecordsView,
	CampaignSentStatsView,
	CampaignDeliveryRecordsView,
	CampaignDeliveryStatsView,
	CampaignReadinessView,
	CampaignValidateView,
	CampaignActivateView,
	CampaignPauseView,
	CampaignResumeView,
	CampaignCompleteView,
	CampaignCancelView,
	DatabaseConfigListCreateView,
	DatabaseConfigDetailView,
	DatabaseConfigTestView,
	DatabaseConfigTestParamsView,
	DatabaseConfigTablesView,
	DatabaseConfigColumnsView,
	DatabaseConfigPreviewView,
	CustomerProfileConfigListCreateView,
	CustomerProfileConfigDetailView,
	CustomerProfilePreviewView,
	CampaignAudienceView,
	CampaignAudienceMembersView,
	AudienceConfigCreateView,
	AudienceConfigPreviewView,
	AudienceBuildView,
	ManualAudienceApiView,
	FileAudienceApiView,
	DatabaseAudienceApiView,
	CampaignBuildMessagesView,
	CampaignMessagesListView,
	CampaignMessagesStatsView,
	CampaignMessagesClearView,
	SenderIDListCreateView,
	SenderIDDetailView,
	SMSCConfigListCreateView,
	SMSCConfigDetailView,
)


urlpatterns = [
	path('databases/', DatabaseConfigListCreateView.as_view(), name='database-list-create'),
	path('databases/test-params/', DatabaseConfigTestParamsView.as_view(), name='database-test-params'),
	path('databases/<int:pk>/', DatabaseConfigDetailView.as_view(), name='database-detail'),
	path('databases/<int:pk>/test/', DatabaseConfigTestView.as_view(), name='database-test'),
	path('databases/<int:pk>/tables/', DatabaseConfigTablesView.as_view(), name='database-tables'),
	path('databases/<int:pk>/tables/<str:table_name>/schema/', DatabaseConfigColumnsView.as_view(), name='database-table-schema'),
	path('databases/<int:pk>/tables/<str:table_name>/preview/', DatabaseConfigPreviewView.as_view(), name='database-table-preview'),
	path('databases/customer-profiles/', CustomerProfileConfigListCreateView.as_view(), name='customer-profile-list-create'),
	path('databases/customer-profiles/<int:pk>/', CustomerProfileConfigDetailView.as_view(), name='customer-profile-detail'),
	path('databases/customer-profiles/<int:pk>/preview/', CustomerProfilePreviewView.as_view(), name='customer-profile-preview'),
	path('channels/', ChannelListCreateView.as_view(), name='channel-list-create'),
	path('channels/<int:pk>/', ChannelDetailView.as_view(), name='channel-detail'),
	path('sender-ids/', SenderIDListCreateView.as_view(), name='sender-id-list-create'),
	path('sender-ids/<int:pk>/', SenderIDDetailView.as_view(), name='sender-id-detail'),
	path('smsc-configs/', SMSCConfigListCreateView.as_view(), name='smsc-config-list-create'),
	path('smsc-configs/<int:pk>/', SMSCConfigDetailView.as_view(), name='smsc-config-detail'),
	path('campaigns/', CampaignListCreateView.as_view(), name='campaign-list-create'),
	path(
		'campaigns/<int:campaign_id>/',
		CampaignDetailView.as_view(),
		name='campaign-detail',
	),
	path(
		'campaigns/<int:campaign_id>/hard-delete/',
		CampaignHardDeleteView.as_view(),
		name='campaign-hard-delete',
	),
	path('campaigns/<int:campaign_id>/audience/manual/', ManualAudienceApiView.as_view(), name='campaign-audience-manual'),
	path('campaigns/<int:campaign_id>/audience/file/', FileAudienceApiView.as_view(), name='campaign-audience-file'),
	path('campaigns/<int:campaign_id>/audience/database/', DatabaseAudienceApiView.as_view(), name='campaign-audience-database'),
	path('languages/', LanguageListCreateView.as_view(), name='language-list-create'),
	path(
		'languages/<int:pk>/',
		LanguageDetailView.as_view(),
		name='language-detail',
	),
	path(
		'message-content/languages/',
		MessageLanguageListView.as_view(),
		name='message-language-list',
	),
	path(
		'campaigns/<int:campaign_id>/content/',
		MessageContentDetailView.as_view(),
		name='campaign-message-content',
	),
	path(
		'campaigns/<int:campaign_id>/schedule/',
		ScheduleDetailView.as_view(),
		name='campaign-schedule',
	),
	path(
		'campaigns/<int:campaign_id>/schedule/upcoming/',
		ScheduleUpcomingView.as_view(),
		name='campaign-schedule-upcoming',
	),
	path('delivery-records/', DeliveryRecordListCreateView.as_view(), name='delivery-record-list-create'),
	path('delivery-reports/callback/', DeliveryReportCallbackView.as_view(), name='delivery-report-callback'),
	path('sent-records/', SentRecordListCreateView.as_view(), name='sent-record-list-create'),
	path('sent-records/bulk/', SentRecordBulkCreateView.as_view(), name='sent-record-bulk-create'),
	path('sent-records/bulk-update/', SentRecordBulkUpdateView.as_view(), name='sent-record-bulk-update'),
	path('sent-records/<int:pk>/', SentRecordDetailView.as_view(), name='sent-record-detail'),
	path('campaigns/<int:campaign_id>/sent-records/', CampaignSentRecordsView.as_view(), name='campaign-sent-records'),
	path('campaigns/<int:campaign_id>/sent-stats/', CampaignSentStatsView.as_view(), name='campaign-sent-stats'),
	path('delivery-records/bulk/', DeliveryRecordBulkCreateView.as_view(), name='delivery-record-bulk-create'),
	path('delivery-records/bulk-update/', DeliveryRecordBulkUpdateView.as_view(), name='delivery-record-bulk-update'),
	path('delivery-records/<int:pk>/', DeliveryRecordDetailView.as_view(), name='delivery-record-detail'),
	path('campaigns/<int:campaign_id>/delivery-records/', CampaignDeliveryRecordsView.as_view(), name='campaign-delivery-records'),
	path('campaigns/<int:campaign_id>/delivery-stats/', CampaignDeliveryStatsView.as_view(), name='campaign-delivery-stats'),
	path('campaigns/<int:campaign_id>/readiness/', CampaignReadinessView.as_view(), name='campaign-readiness'),
	path('campaigns/<int:campaign_id>/validate/', CampaignValidateView.as_view(), name='campaign-validate'),
	path('campaigns/<int:campaign_id>/activate/', CampaignActivateView.as_view(), name='campaign-activate'),
	path('campaigns/<int:campaign_id>/pause/', CampaignPauseView.as_view(), name='campaign-pause'),
	path('campaigns/<int:campaign_id>/resume/', CampaignResumeView.as_view(), name='campaign-resume'),
	path('campaigns/<int:campaign_id>/complete/', CampaignCompleteView.as_view(), name='campaign-complete'),
	path('campaigns/<int:campaign_id>/cancel/', CampaignCancelView.as_view(), name='campaign-cancel'),
	path('campaigns/<int:campaign_id>/audience/', CampaignAudienceView.as_view(), name='campaign-audience'),
	path('campaigns/<int:campaign_id>/audience/members/', CampaignAudienceMembersView.as_view(), name='campaign-audience-members'),
	path('campaigns/<int:campaign_id>/audience-config/', AudienceConfigCreateView.as_view(), name='campaign-audience-config'),
	path('campaigns/<int:campaign_id>/audience-config/preview/', AudienceConfigPreviewView.as_view(), name='campaign-audience-config-preview'),
	path('audience-configs/<int:pk>/build/', AudienceBuildView.as_view(), name='audience-build'),
	path('campaigns/<int:pk>/messages/build/', CampaignBuildMessagesView.as_view(), name='campaign-messages-build'),
	path('campaigns/<int:pk>/messages/', CampaignMessagesListView.as_view(), name='campaign-messages-list'),
	path('campaigns/<int:pk>/messages/stats/', CampaignMessagesStatsView.as_view(), name='campaign-messages-stats'),
	path('campaigns/<int:pk>/messages/clear/', CampaignMessagesClearView.as_view(), name='campaign-messages-clear'),
]
