from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .test_sms_views import TestMessageDetailView, TestMessageListCreateView, TestMessageResendView

from .views import (
	UserRegistrationView,
	CampaignLoginView,
	CampaignInitialPasswordChangeView,
	CurrentUserView,
	PasswordChangeView,
	UserAdminListCreateView,
	UserAdminDetailView,
	CampaignDetailView,
	CampaignHardDeleteView,
	CampaignListCreateView,
	DashboardView,
	ChannelDetailView,
	ChannelListCreateView,
	LanguageDetailView,
	LanguageListCreateView,
	MessageContentDetailView,
	MessageContentCollectionView,
	MessageContentResourceView,
	MessageLanguageListView,
	ScheduleDetailView,
	ScheduleCollectionView,
	ScheduleSummaryView,
	ScheduleDueNowView,
	ScheduleResourceView,
	ScheduleUpcomingWindowsView,
	ScheduleActivationView,
	ScheduleDeactivationView,
	ScheduleResetView,
	ScheduleUpcomingView,
	CampaignReadinessView,
	CampaignValidateView,
	CampaignActivateView,
	CampaignStartView,
	CampaignSendNowView,
	CampaignPauseView,
	CampaignResumeView,
	CampaignCompleteView,
	CampaignCancelView,
	DatabaseConfigListCreateView,
	DatabaseConfigDetailView,
	DatabaseConfigTestView,
	DatabaseConfigTestParamsView,
	DatabaseConfigTablesView,
	DatabaseConfigColumnsView,
	DatabaseConfigPreviewView,
	CustomerProfileConfigListCreateView,
	CustomerProfileConfigDetailView,
	CustomerProfilePreviewView,
	AudienceCollectionView,
	AudienceSummaryView,
	AudienceResourceView,
	AudienceStatisticsView,
	AudienceRecipientsPreviewView,
	CampaignAudienceView,
	CampaignAudienceMembersView,
	CampaignAudienceRoundsView,
	AudienceConfigCreateView,
	AudienceConfigPreviewView,
	AudienceBuildView,
	AudienceConfigProgressView,
	AudienceBuildJobView,
	ManualAudienceApiView,
	FileAudienceApiView,
	DatabaseAudienceApiView,
	CampaignBuildMessagesView,
	CampaignMessageBuildProgressView,
	CampaignProgressView,
	CampaignMessagesBatchesView,
	CampaignMessagesListView,
	CampaignMessagesStatsView,
	CampaignMessagesClearView,
	SenderIDListCreateView,
	SenderIDDetailView,
	SMSCConfigListCreateView,
	SMSCConfigDetailView,
	GlobalTPSConfigListCreateView,
	GlobalTPSConfigDetailView,
	GlobalTPSConfigActiveView,
	NAddressesConfigListCreateView,
	NAddressesConfigDetailView,
	NAddressesConfigActiveView,
	EmailConfigListCreateView,
	EmailConfigDetailView,
	EmailConfigTestView,
	CampaignProgressReportListCreateView,
	CampaignProgressReportDetailView,
	CampaignEmailReportView,
	CampaignEmailReportHistoryView,
	EmailReportResendView,
	ReportSubscriptionListCreateView,
	ReportSubscriptionDetailView,
	ReportSubscriptionDueNowView,
	ReportSubscriptionSendNowView,
	ReportDeliveryLogDetailView,
)


urlpatterns = [
	path('test-sms/', TestMessageListCreateView.as_view(), name='test-sms-list-create'),
	path('test-sms/<int:pk>/', TestMessageDetailView.as_view(), name='test-sms-detail'),
	path('test-sms/<int:pk>/resend/', TestMessageResendView.as_view(), name='test-sms-resend'),
	path('auth/register/', UserRegistrationView.as_view(), name='user-register'),
	path('auth/login/', CampaignLoginView.as_view(), name='token-obtain-pair'),
	path('auth/initial-password/', CampaignInitialPasswordChangeView.as_view(), name='initial-password-change'),
	path('auth/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
	path('auth/me/', CurrentUserView.as_view(), name='current-user'),
	path('auth/password/', PasswordChangeView.as_view(), name='password-change'),
	path('auth/users/', UserAdminListCreateView.as_view(), name='user-admin-list-create'),
	path('auth/users/<int:pk>/', UserAdminDetailView.as_view(), name='user-admin-detail'),
	path('databases/', DatabaseConfigListCreateView.as_view(), name='database-list-create'),
	path('databases/test-params/', DatabaseConfigTestParamsView.as_view(), name='database-test-params'),
	path('databases/<int:pk>/', DatabaseConfigDetailView.as_view(), name='database-detail'),
	path('databases/<int:pk>/test/', DatabaseConfigTestView.as_view(), name='database-test'),
	path('databases/<int:pk>/tables/', DatabaseConfigTablesView.as_view(), name='database-tables'),
	path('databases/<int:pk>/tables/<str:table_name>/schema/', DatabaseConfigColumnsView.as_view(), name='database-table-schema'),
	path('databases/<int:pk>/tables/<str:table_name>/preview/', DatabaseConfigPreviewView.as_view(), name='database-table-preview'),
	path('databases/customer-profiles/', CustomerProfileConfigListCreateView.as_view(), name='customer-profile-list-create'),
	path('databases/customer-profiles/<int:pk>/', CustomerProfileConfigDetailView.as_view(), name='customer-profile-detail'),
	path('databases/customer-profiles/<int:pk>/preview/', CustomerProfilePreviewView.as_view(), name='customer-profile-preview'),
	path('channels/', ChannelListCreateView.as_view(), name='channel-list-create'),
	path('channels/<int:pk>/', ChannelDetailView.as_view(), name='channel-detail'),
	path('sender-ids/', SenderIDListCreateView.as_view(), name='sender-id-list-create'),
	path('sender-ids/<int:pk>/', SenderIDDetailView.as_view(), name='sender-id-detail'),
	path('smsc-configs/', SMSCConfigListCreateView.as_view(), name='smsc-config-list-create'),
	path('smsc-configs/<int:pk>/', SMSCConfigDetailView.as_view(), name='smsc-config-detail'),
	path('global-tps-config/', GlobalTPSConfigListCreateView.as_view(), name='global-tps-config-list-create'),
	path('global-tps-config/active/', GlobalTPSConfigActiveView.as_view(), name='global-tps-config-active'),
	path('global-tps-config/<int:pk>/', GlobalTPSConfigDetailView.as_view(), name='global-tps-config-detail'),
	path('n-addresses-config/', NAddressesConfigListCreateView.as_view(), name='n-addresses-config-list-create'),
	path('n-addresses-config/active/', NAddressesConfigActiveView.as_view(), name='n-addresses-config-active'),
	path('n-addresses-config/<int:pk>/', NAddressesConfigDetailView.as_view(), name='n-addresses-config-detail'),
	path('email-config/', EmailConfigListCreateView.as_view(), name='email-config-list-create'),
	path('email-config/test/', EmailConfigTestView.as_view(), name='email-config-test'),
	path('email-config/<int:pk>/', EmailConfigDetailView.as_view(), name='email-config-detail'),
	path('email-config/<int:pk>/test/', EmailConfigTestView.as_view(), name='email-config-detail-test'),
	path('email-reports/', CampaignProgressReportListCreateView.as_view(), name='email-report-list-create'),
	path('email-reports/<int:pk>/', CampaignProgressReportDetailView.as_view(), name='email-report-detail'),
	path('report-subscriptions/', ReportSubscriptionListCreateView.as_view(), name='report-subscription-list-create'),
	path('report-subscriptions/due-now/', ReportSubscriptionDueNowView.as_view(), name='report-subscription-due-now'),
	path('report-subscriptions/<int:pk>/', ReportSubscriptionDetailView.as_view(), name='report-subscription-detail'),
	path('report-subscriptions/<int:pk>/send-now/', ReportSubscriptionSendNowView.as_view(), name='report-subscription-send-now'),
	path('report-delivery-logs/<int:pk>/', ReportDeliveryLogDetailView.as_view(), name='report-delivery-log-detail'),
	path('report-delivery-logs/<int:pk>/resend/', EmailReportResendView.as_view(), name='email-report-resend'),
	path('audiences/', AudienceCollectionView.as_view(), name='audience-list'),
	path('audiences/summary/', AudienceSummaryView.as_view(), name='audience-summary'),
	path('audiences/<int:pk>/statistics/', AudienceStatisticsView.as_view(), name='audience-statistics'),
	path('audiences/<int:pk>/recipients_preview/', AudienceRecipientsPreviewView.as_view(), name='audience-recipients-preview'),
	path('audiences/<int:pk>/', AudienceResourceView.as_view(), name='audience-detail'),
	path('campaigns/', CampaignListCreateView.as_view(), name='campaign-list-create'),
	path('dashboard/', DashboardView.as_view(), name='campaign-dashboard'),
	path(
		'campaigns/<int:campaign_id>/',
		CampaignDetailView.as_view(),
		name='campaign-detail',
	),
	path(
		'campaigns/<int:campaign_id>/hard-delete/',
		CampaignHardDeleteView.as_view(),
		name='campaign-hard-delete',
	),
	path('campaigns/<int:campaign_id>/audience/manual/', ManualAudienceApiView.as_view(), name='campaign-audience-manual'),
	path('campaigns/<int:campaign_id>/audience/file/', FileAudienceApiView.as_view(), name='campaign-audience-file'),
	path('campaigns/<int:campaign_id>/audience/database/', DatabaseAudienceApiView.as_view(), name='campaign-audience-database'),
	path('languages/', LanguageListCreateView.as_view(), name='language-list-create'),
	path(
		'languages/<int:pk>/',
		LanguageDetailView.as_view(),
		name='language-detail',
	),
	path(
		'message-content/',
		MessageContentCollectionView.as_view(),
		name='message-content-list-create',
	),
	path(
		'message-content/<int:pk>/',
		MessageContentResourceView.as_view(),
		name='message-content-detail',
	),
	path(
		'message-content/languages/',
		MessageLanguageListView.as_view(),
		name='message-language-list',
	),
	path(
		'campaigns/<int:campaign_id>/content/',
		MessageContentDetailView.as_view(),
		name='campaign-message-content',
	),
	path(
		'schedules/',
		ScheduleCollectionView.as_view(),
		name='schedule-list-create',
	),
	path('schedules/due-now/', ScheduleDueNowView.as_view(), name='schedule-due-now'),
	path('schedules/summary/', ScheduleSummaryView.as_view(), name='schedule-summary'),
	path(
		'schedules/<int:pk>/upcoming_windows/',
		ScheduleUpcomingWindowsView.as_view(),
		name='schedule-upcoming-windows',
	),
	path('schedules/<int:pk>/activate/', ScheduleActivationView.as_view(), name='schedule-activate'),
	path('schedules/<int:pk>/deactivate/', ScheduleDeactivationView.as_view(), name='schedule-deactivate'),
	path('schedules/<int:pk>/reset/', ScheduleResetView.as_view(), name='schedule-reset'),
	path('schedules/<int:pk>/', ScheduleResourceView.as_view(), name='schedule-detail'),
	path(
		'campaigns/<int:campaign_id>/schedule/',
		ScheduleDetailView.as_view(),
		name='campaign-schedule',
	),
	path(
		'campaigns/<int:campaign_id>/schedule/upcoming/',
		ScheduleUpcomingView.as_view(),
		name='campaign-schedule-upcoming',
	),
	path('campaigns/<int:campaign_id>/readiness/', CampaignReadinessView.as_view(), name='campaign-readiness'),
	path('campaigns/<int:campaign_id>/validate/', CampaignValidateView.as_view(), name='campaign-validate'),
	path('campaigns/<int:campaign_id>/activate/', CampaignActivateView.as_view(), name='campaign-activate'),
	path('campaigns/<int:campaign_id>/start/', CampaignStartView.as_view(), name='campaign-start'),
	path('campaigns/<int:campaign_id>/send-now/', CampaignSendNowView.as_view(), name='campaign-send-now'),
	path('campaigns/<int:campaign_id>/pause/', CampaignPauseView.as_view(), name='campaign-pause'),
	path('campaigns/<int:campaign_id>/resume/', CampaignResumeView.as_view(), name='campaign-resume'),
	path('campaigns/<int:campaign_id>/complete/', CampaignCompleteView.as_view(), name='campaign-complete'),
	path('campaigns/<int:campaign_id>/cancel/', CampaignCancelView.as_view(), name='campaign-cancel'),
	path('campaigns/<int:campaign_id>/audience/', CampaignAudienceView.as_view(), name='campaign-audience'),
	path('campaigns/<int:campaign_id>/audience/members/', CampaignAudienceMembersView.as_view(), name='campaign-audience-members'),
	path('campaigns/<int:campaign_id>/audience/rounds/', CampaignAudienceRoundsView.as_view(), name='campaign-audience-rounds'),
	path('campaigns/<int:campaign_id>/audience-config/', AudienceConfigCreateView.as_view(), name='campaign-audience-config'),
	path('campaigns/<int:campaign_id>/audience-config/preview/', AudienceConfigPreviewView.as_view(), name='campaign-audience-config-preview'),
	path('audience-configs/<int:pk>/build/', AudienceBuildView.as_view(), name='audience-build'),
	path('audience-configs/<int:pk>/progress/', AudienceConfigProgressView.as_view(), name='audience-progress'),
	path('audience-build-jobs/<int:pk>/', AudienceBuildJobView.as_view(), name='audience-build-job'),
	path('campaigns/<int:pk>/messages/build/', CampaignBuildMessagesView.as_view(), name='campaign-messages-build'),
	path('campaigns/<int:pk>/messages/build-progress/', CampaignMessageBuildProgressView.as_view(), name='campaign-messages-build-progress'),
	path('campaigns/<int:pk>/progress/', CampaignProgressView.as_view(), name='campaign-progress'),
	path('campaigns/<int:pk>/messages/batches/', CampaignMessagesBatchesView.as_view(), name='campaign-messages-batches'),
	path('campaigns/<int:pk>/messages/', CampaignMessagesListView.as_view(), name='campaign-messages-list'),
	path('campaigns/<int:pk>/messages/stats/', CampaignMessagesStatsView.as_view(), name='campaign-messages-stats'),
	path('campaigns/<int:pk>/messages/clear/', CampaignMessagesClearView.as_view(), name='campaign-messages-clear'),
	path('campaigns/<int:campaign_id>/reports/email/', CampaignEmailReportView.as_view(), name='campaign-email-report'),
	path('campaigns/<int:campaign_id>/report-history/', CampaignEmailReportHistoryView.as_view(), name='campaign-email-report-history'),
]
