# Generated by Django 5.2.15 on 2026-09-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='audience_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of Audience IDs belonging to this campaign.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='message_content_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the MessageContent child row for this campaign.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedule_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the Schedule child row for this campaign.', null=True),
        ),
    ]
