# Generated by Django 5.2.15 on 2026-09-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0002_campaign_audience_ids_campaign_message_content_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='audience_ids',
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the Audience child row for this campaign.', null=True),
        ),
    ]
