# Generated by Django 5.2.15 on 2026-09-13 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0003_remove_campaign_audience_ids_campaign_audience_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='audience_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='message_content_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='schedule_id',
        ),
        migrations.AlterField(
            model_name='audience',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='sms_campaign_manager.campaign'),
        ),
        migrations.AlterField(
            model_name='messagecontent',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_content', to='sms_campaign_manager.campaign'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='sms_campaign_manager.campaign'),
        ),
    ]
