# Generated by Django 5.2.15 on 2026-09-14 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0004_remove_campaign_audience_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('manual', 'Manual Entry'), ('file_import', 'File Import'), ('database', 'Database Source')], db_index=True, default='manual', max_length=20)),
                ('source_table', models.CharField(blank=True, default='', help_text='Table name (for database source)', max_length=200)),
                ('source_msisdn_column', models.CharField(blank=True, default='msisdn', help_text='MSISDN column in source table', max_length=100)),
                ('source_language_column', models.CharField(blank=True, default='', help_text='Language column in source table (optional)', max_length=100)),
                ('source_filter_clause', models.TextField(blank=True, default='', help_text='Optional SQL WHERE clause without the word WHERE')),
                ('manual_msisdns', models.JSONField(blank=True, default=list, help_text='List of MSISDNs (for manual source)')),
                ('manual_languages', models.JSONField(blank=True, default=list, help_text='Optional matching list of languages (for manual source)')),
                ('source_file_path', models.CharField(blank=True, default='', help_text='Path to uploaded file', max_length=500)),
                ('source_file_msisdn_column', models.CharField(blank=True, default='', help_text='MSISDN column in file', max_length=100)),
                ('source_file_language_column', models.CharField(blank=True, default='', help_text='Language column in file (optional)', max_length=100)),
                ('mapper_enabled', models.BooleanField(default=False, help_text='Whether to join with a language mapper table')),
                ('mapper_table', models.CharField(blank=True, default='', help_text='Mapper table name', max_length=200)),
                ('mapper_msisdn_column', models.CharField(blank=True, default='', help_text='MSISDN column in mapper table (JOIN key)', max_length=100)),
                ('mapper_language_column', models.CharField(blank=True, default='', help_text='Language column in mapper table', max_length=100)),
                ('mapper_join_type', models.CharField(choices=[('LEFT', 'LEFT JOIN'), ('INNER', 'INNER JOIN')], default='LEFT', help_text='JOIN type between source and mapper', max_length=10)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('language_from_source', models.PositiveIntegerField(default=0)),
                ('language_from_mapper', models.PositiveIntegerField(default=0)),
                ('language_from_default', models.PositiveIntegerField(default=0)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('last_built_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience_config', to='sms_campaign_manager.campaign')),
                ('default_language', models.ForeignKey(help_text='Fallback when no source/mapper provides language', on_delete=django.db.models.deletion.PROTECT, related_name='audience_configs', to='sms_campaign_manager.language')),
                ('mapper_database', models.ForeignKey(blank=True, help_text='Database containing mapper table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapper_audience_configs', to='sms_campaign_manager.databaseconfig')),
                ('source_database', models.ForeignKey(blank=True, help_text='For database source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_audience_configs', to='sms_campaign_manager.databaseconfig')),
            ],
            options={
                'verbose_name': 'Audience Configuration',
                'verbose_name_plural': 'Audience Configurations',
            },
        ),
    ]
