# Generated by Django 5.2.15 on 2026-09-14 08:32

from django.db import migrations


def seed_languages(apps, schema_editor):
    Language = apps.get_model('sms_campaign_manager', 'Language')
    for code, name in [
        ('en', 'English'),
        ('am', 'Amharic'),
        ('ti', 'Tigrinya'),
        ('om', 'Oromo'),
        ('so', 'Somali'),
    ]:
        Language.objects.get_or_create(code=code, defaults={'name': name, 'is_active': True})


def reverse_seed_languages(apps, schema_editor):
    Language = apps.get_model('sms_campaign_manager', 'Language')
    Language.objects.filter(code__in=['en', 'am', 'ti', 'om', 'so']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0005_audienceconfig'),
    ]

    operations = [
        migrations.RunPython(seed_languages, reverse_seed_languages),
    ]
