# Generated by Django 5.2.15 on 2026-09-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0006_seed_supported_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_members', to='sms_campaign_manager.campaign'),
        ),
    ]
