# Generated by Django 5.2.15 on 2026-09-17 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0007_alter_audience_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReportInbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider_message_id', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='sms_campaig_status_4e1a89_idx'), models.Index(fields=['provider_message_id', 'status'], name='sms_campaig_provide_63b1ac_idx')],
            },
        ),
    ]
