# Generated by Django 4.2.7 on 2026-09-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0007_alter_audience_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='audienceconfig',
            name='rebuild_before_each_run',
            field=models.BooleanField(default=False, help_text='Rebuild the audience from its source before each scheduled run'),
        ),
        migrations.AddField(
            model_name='audienceconfig',
            name='rebuild_minutes_before',
            field=models.PositiveSmallIntegerField(default=10, help_text='Minutes before the scheduled start to begin rebuilding'),
        ),
        migrations.AddField(
            model_name='audienceconfig',
            name='rebuild_timeout_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Maximum allowed audience rebuild duration in minutes'),
        ),
    ]
