# Generated by Django 4.2.7 on 2026-09-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0008_audienceconfig_rebuild_before_each_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='owner_emails',
            field=models.JSONField(blank=True, default=list, help_text='Email addresses that receive campaign notifications'),
        ),
    ]
