# Generated by Django 4.2.7 on 2026-09-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0009_campaign_owner_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceBuildJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('processed_rows', models.PositiveBigIntegerField(default=0)),
                ('valid_rows', models.PositiveBigIntegerField(default=0)),
                ('invalid_rows', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_jobs', to='sms_campaign_manager.audienceconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audience_config', 'status'], name='sms_campaig_audienc_1d9423_idx')],
            },
        ),
    ]
