# Generated by Django 5.2.15 on 2026-09-20 10:25

import django.db.models.deletion
import sms_campaign_manager.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0009_kafkaoutboxevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaignReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('10m', 'Every 10 minutes'), ('1h', 'Every hour'), ('daily', 'Daily')], default='daily', max_length=10)),
                ('include_owner', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaignReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EmailServerConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', sms_campaign_manager.fields.EncryptedCharField(blank=True, default='', max_length=500)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='kafkaoutboxevent',
            new_name='sms_campaig_status_36e599_idx',
            old_name='sms_kafka_status_avail_idx',
        ),
        migrations.RenameIndex(
            model_name='kafkaoutboxevent',
            new_name='sms_campaig_event_t_4c7b23_idx',
            old_name='sms_kafka_event_status_idx',
        ),
        migrations.AddField(
            model_name='emailcampaignreport',
            name='campaigns',
            field=models.ManyToManyField(blank=True, related_name='email_reports', to='sms_campaign_manager.campaign'),
        ),
        migrations.AddField(
            model_name='emailcampaignreport',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaign_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaignreportrecipient',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sms_campaign_manager.emailcampaignreport'),
        ),
        migrations.AddField(
            model_name='emailcampaignreport',
            name='email_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='sms_campaign_manager.emailserverconfig'),
        ),
        migrations.AddConstraint(
            model_name='emailcampaignreportrecipient',
            constraint=models.UniqueConstraint(fields=('report', 'email'), name='unique_report_recipient'),
        ),
    ]
