# Generated by Django 5.2.15 on 2026-09-20 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0011_emailconfig_emailreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignProgressReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('recipients', models.JSONField(default=list)),
                ('include_campaign_owners', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('10_minutes', 'Every 10 minutes'), ('hourly', 'Every hour'), ('daily', 'Daily')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaigns', models.ManyToManyField(related_name='progress_reports', to='sms_campaign_manager.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_progress_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
