# Generated by Django 4.2.7 on 2026-09-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0012_campaignprogressreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageobject',
            name='locked_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='messageobject',
            name='sending_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='messageobject',
            name='worker_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
