# Generated by Django 4.2.7 on 2026-09-26 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms_campaign_manager', '0016_round_aware_audience_rebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessSent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('recipient', models.CharField(db_index=True, max_length=20)),
                ('sender_id', models.CharField(max_length=11)),
                ('batch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('total_attempts', models.PositiveSmallIntegerField(default=1)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('provider_status', models.CharField(blank=True, default='', max_length=50)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms_campaign_manager.campaign')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms_campaign_manager.channel')),
            ],
            options={
                'db_table': 'sms_campaign_manager_successsent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, max_length=100)),
                ('provider_message_id', models.CharField(db_index=True, max_length=100)),
                ('recipient', models.CharField(db_index=True, max_length=20)),
                ('sender_id', models.CharField(max_length=11)),
                ('delivery_status', models.CharField(db_index=True, max_length=20)),
                ('delivery_code', models.CharField(blank=True, default='', max_length=20)),
                ('delivery_description', models.TextField(blank=True, default='')),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms_campaign_manager.campaign')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms_campaign_manager.channel')),
            ],
            options={
                'db_table': 'sms_campaign_manager_successdelivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipients', models.JSONField(default=list)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('on_completion', 'On completion'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('format', models.CharField(choices=[('text', 'Plain text'), ('html', 'HTML'), ('csv', 'CSV'), ('pdf', 'PDF')], default='html', max_length=10)),
                ('include_sent_stats', models.BooleanField(default=True)),
                ('include_delivery_stats', models.BooleanField(default=True)),
                ('include_message_stats', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_subscriptions', to='sms_campaign_manager.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FailedSent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('recipient', models.CharField(db_index=True, max_length=20)),
                ('sender_id', models.CharField(max_length=11)),
                ('batch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('total_attempts', models.PositiveSmallIntegerField(default=1)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('provider_status', models.CharField(blank=True, default='', max_length=50)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('final_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms_campaign_manager.campaign')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms_campaign_manager.channel')),
            ],
            options={
                'db_table': 'sms_campaign_manager_failedsent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FailedDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, max_length=100)),
                ('provider_message_id', models.CharField(db_index=True, max_length=100)),
                ('recipient', models.CharField(db_index=True, max_length=20)),
                ('sender_id', models.CharField(max_length=11)),
                ('delivery_status', models.CharField(db_index=True, max_length=20)),
                ('delivery_code', models.CharField(blank=True, default='', max_length=20)),
                ('delivery_description', models.TextField(blank=True, default='')),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms_campaign_manager.campaign')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms_campaign_manager.channel')),
            ],
            options={
                'db_table': 'sms_campaign_manager_faileddelivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDeliveryLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipients', models.JSONField(default=list)),
                ('format', models.CharField(choices=[('text', 'Plain text'), ('html', 'HTML'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='failed', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attachment_names', models.JSONField(blank=True, default=list)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('include_sent_stats', models.BooleanField(default=True)),
                ('include_delivery_stats', models.BooleanField(default=True)),
                ('include_message_stats', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_delivery_logs', to='sms_campaign_manager.campaign')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='sms_campaign_manager.reportsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', '-created_at'], name='sms_campaig_campaig_3687b0_idx')],
            },
        ),
    ]
