# Generated by Django 4.2.7 on 2026-09-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0017_successsent_successdelivery_reportsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='last_test_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='last_test_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='last_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='auto_reset',
            field=models.BooleanField(default=True),
        ),
    ]
