# Generated by Django 5.2.15 on 2026-09-29 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0021_message_build_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTPSConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('global_tps', models.PositiveIntegerField(default=4000)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_global_tps_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global TPS Config',
                'verbose_name_plural': 'Global TPS Configs',
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['is_active'], name='sms_campaig_is_acti_d2816d_idx'), models.Index(fields=['is_default'], name='sms_campaig_is_defa_2dd780_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_global_tps_default')],
            },
        ),
        migrations.CreateModel(
            name='NAddressesConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('max_addresses_per_request', models.PositiveIntegerField(default=1000)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_n_addresses_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'N-Addresses Config',
                'verbose_name_plural': 'N-Addresses Configs',
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['is_active'], name='sms_campaig_is_acti_825eaf_idx'), models.Index(fields=['is_default'], name='sms_campaig_is_defa_390b83_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_n_addresses_default')],
            },
        ),
    ]
