# Generated by Django 5.2.15 on 2026-09-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0022_globaltpsconfig_naddressesconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faileddelivery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Failed Delivery', 'verbose_name_plural': 'Failed Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='failedsent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Failed Sent', 'verbose_name_plural': 'Failed Sents'},
        ),
        migrations.AlterModelOptions(
            name='successdelivery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Success Delivery', 'verbose_name_plural': 'Success Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='successsent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Success Sent', 'verbose_name_plural': 'Success Sents'},
        ),
        migrations.RemoveIndex(
            model_name='messageobject',
            name='sms_campaig_campaig_e4456a_idx',
        ),
        migrations.RemoveIndex(
            model_name='messageobject',
            name='sms_campaig_campaig_e08760_idx',
        ),
        migrations.RemoveIndex(
            model_name='messageobject',
            name='sms_campaig_recipie_f5246b_idx',
        ),
        migrations.RemoveIndex(
            model_name='messageobject',
            name='sms_campaig_deliver_528ca6_idx',
        ),
        migrations.RemoveIndex(
            model_name='messageobject',
            name='sms_campaig_channel_3adfca_idx',
        ),
        migrations.RemoveIndex(
            model_name='messageobject',
            name='sms_campaig_languag_bec3ef_idx',
        ),
        migrations.RemoveField(
            model_name='faileddelivery',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='messageobject',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='messageobject',
            name='delivery_attempts',
        ),
        migrations.RemoveField(
            model_name='messageobject',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='messageobject',
            name='failed_at',
        ),
        migrations.RemoveField(
            model_name='messageobject',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='messageobject',
            name='message_parts',
        ),
        migrations.RemoveField(
            model_name='messageobject',
            name='personalized_fields',
        ),
        migrations.RemoveField(
            model_name='messageobject',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='successdelivery',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='done_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='error_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='event',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='raw_dlr_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='round_number',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failedsent',
            name='built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failedsent',
            name='error_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='failedsent',
            name='http_status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failedsent',
            name='message_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='failedsent',
            name='message_parts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='failedsent',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='failedsent',
            name='round_number',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='failedsent',
            name='sending_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failedsent',
            name='servicetag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='failedsent',
            name='servicetype',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='failedsent',
            name='worker_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='messageobject',
            name='round_number',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Which round of the campaign this message belongs to'),
        ),
        migrations.AddField(
            model_name='smscconfig',
            name='max_addresses_per_request',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum number of destinations per HTTP request to the SMSC'),
        ),
        migrations.AddField(
            model_name='successdelivery',
            name='done_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='successdelivery',
            name='event',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='successdelivery',
            name='raw_dlr_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='successdelivery',
            name='round_number',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='successdelivery',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='successsent',
            name='built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='successsent',
            name='message_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='successsent',
            name='message_parts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='successsent',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='successsent',
            name='round_number',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='successsent',
            name='sending_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='successsent',
            name='servicetag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='successsent',
            name='servicetype',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='successsent',
            name='worker_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faileddelivery',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failed_delivery_messages', to='sms_campaign_manager.campaign'),
        ),
        migrations.AlterField(
            model_name='faileddelivery',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failed_delivery_messages', to='sms_campaign_manager.channel'),
        ),
        migrations.AlterField(
            model_name='failedsent',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failed_sent_messages', to='sms_campaign_manager.campaign'),
        ),
        migrations.AlterField(
            model_name='failedsent',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failed_sent_messages', to='sms_campaign_manager.channel'),
        ),
        migrations.AlterField(
            model_name='failedsent',
            name='final_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='failedsent',
            name='total_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='messageobject',
            name='message_content',
            field=models.TextField(help_text='Fully personalized message content for this recipient'),
        ),
        migrations.AlterField(
            model_name='messageobject',
            name='recipient',
            field=models.CharField(db_index=True, help_text='Recipient MSISDN (digits only, no +)', max_length=20),
        ),
        migrations.AlterField(
            model_name='messageobject',
            name='sent_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='successdelivery',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='success_delivery_messages', to='sms_campaign_manager.campaign'),
        ),
        migrations.AlterField(
            model_name='successdelivery',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='success_delivery_messages', to='sms_campaign_manager.channel'),
        ),
        migrations.AlterField(
            model_name='successdelivery',
            name='delivery_status',
            field=models.CharField(db_index=True, default='DELIVERED', max_length=20),
        ),
        migrations.AlterField(
            model_name='successsent',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='success_sent_messages', to='sms_campaign_manager.campaign'),
        ),
        migrations.AlterField(
            model_name='successsent',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='success_sent_messages', to='sms_campaign_manager.channel'),
        ),
        migrations.AddIndex(
            model_name='faileddelivery',
            index=models.Index(fields=['campaign', 'failed_at'], name='sms_campaig_campaig_3b948a_idx'),
        ),
        migrations.AddIndex(
            model_name='faileddelivery',
            index=models.Index(fields=['delivery_status', 'campaign'], name='sms_campaig_deliver_cf097d_idx'),
        ),
        migrations.AddIndex(
            model_name='faileddelivery',
            index=models.Index(fields=['provider_message_id'], name='sms_campaig_provide_ffda69_idx'),
        ),
        migrations.AddIndex(
            model_name='faileddelivery',
            index=models.Index(fields=['-created_at'], name='sms_campaig_created_071b40_idx'),
        ),
        migrations.AddIndex(
            model_name='failedsent',
            index=models.Index(fields=['campaign', 'final_attempt_at'], name='sms_campaig_campaig_f9a5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='failedsent',
            index=models.Index(fields=['error_type', 'campaign'], name='sms_campaig_error_t_d4f0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='failedsent',
            index=models.Index(fields=['provider_message_id'], name='sms_campaig_provide_631c10_idx'),
        ),
        migrations.AddIndex(
            model_name='failedsent',
            index=models.Index(fields=['-created_at'], name='sms_campaig_created_6da512_idx'),
        ),
        migrations.AddIndex(
            model_name='messageobject',
            index=models.Index(fields=['campaign', 'round_number'], name='sms_campaig_campaig_e0d1df_idx'),
        ),
        migrations.AddIndex(
            model_name='messageobject',
            index=models.Index(fields=['locked_until'], name='sms_campaig_locked__d6d2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='successdelivery',
            index=models.Index(fields=['campaign', 'delivered_at'], name='sms_campaig_campaig_8ca701_idx'),
        ),
        migrations.AddIndex(
            model_name='successdelivery',
            index=models.Index(fields=['provider_message_id'], name='sms_campaig_provide_1deb78_idx'),
        ),
        migrations.AddIndex(
            model_name='successdelivery',
            index=models.Index(fields=['delivery_status'], name='sms_campaig_deliver_3d49dc_idx'),
        ),
        migrations.AddIndex(
            model_name='successdelivery',
            index=models.Index(fields=['-created_at'], name='sms_campaig_created_246319_idx'),
        ),
        migrations.AddIndex(
            model_name='successsent',
            index=models.Index(fields=['campaign', 'sent_at'], name='sms_campaig_campaig_c4eadb_idx'),
        ),
        migrations.AddIndex(
            model_name='successsent',
            index=models.Index(fields=['provider_message_id'], name='sms_campaig_provide_22d577_idx'),
        ),
        migrations.AddIndex(
            model_name='successsent',
            index=models.Index(fields=['recipient', 'campaign'], name='sms_campaig_recipie_005397_idx'),
        ),
        migrations.AddIndex(
            model_name='successsent',
            index=models.Index(fields=['-created_at'], name='sms_campaig_created_d206dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='faileddelivery',
            constraint=models.UniqueConstraint(fields=('message_id', 'provider_message_id'), name='unique_failed_delivery_per_message'),
        ),
        migrations.AddConstraint(
            model_name='successdelivery',
            constraint=models.UniqueConstraint(fields=('message_id', 'provider_message_id'), name='unique_success_delivery_per_message'),
        ),
        migrations.AlterModelTable(
            name='faileddelivery',
            table=None,
        ),
        migrations.AlterModelTable(
            name='failedsent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='successdelivery',
            table=None,
        ),
        migrations.AlterModelTable(
            name='successsent',
            table=None,
        ),
    ]
