# Generated by Django 4.2.7 on 2026-09-29 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0023_alter_faileddelivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubscription',
            name='campaigns',
            field=models.ManyToManyField(blank=True, related_name='multi_campaign_report_subscriptions', to='sms_campaign_manager.campaign'),
        ),
        migrations.AddField(
            model_name='reportsubscription',
            name='email_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_subscriptions', to='sms_campaign_manager.emailconfig'),
        ),
        migrations.AddField(
            model_name='reportsubscription',
            name='include_campaign_owners',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportsubscription',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
