# Generated by Django 4.2.7 on 2026-09-29 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms_campaign_manager', '0024_reportsubscription_campaigns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender_id', models.CharField(max_length=11)),
                ('recipient', models.CharField(db_index=True, max_length=20)),
                ('channel_code', models.CharField(max_length=30)),
                ('message_content', models.TextField()),
                ('test_campaign_id', models.IntegerField(default=9999)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('provider_status', models.CharField(blank=True, default='', max_length=50)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('request_url', models.CharField(blank=True, default='', max_length=500)),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Message',
                'verbose_name_plural': 'Test Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sms_campaig_created_ccb37d_idx'), models.Index(fields=['provider_message_id'], name='sms_campaig_provide_6871bb_idx')],
            },
        ),
    ]
