# Generated by Django 4.2.7 on 2026-09-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0025_testmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdeliverylog',
            name='format',
            field=models.CharField(choices=[('text', 'Plain text'), ('html', 'HTML'), ('csv', 'CSV')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reportsubscription',
            name='format',
            field=models.CharField(choices=[('text', 'Plain text'), ('html', 'HTML'), ('csv', 'CSV')], default='html', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportsubscription',
            name='frequency',
            field=models.CharField(choices=[('10min', 'Every 10 minutes'), ('1hr', 'Every hour'), ('1day', 'Every day'), ('manual', 'Manual only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('on_completion', 'On completion')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportsubscription',
            name='include_campaign_owners',
            field=models.BooleanField(default=True),
        ),
    ]
