# Generated by Django 4.2.7 on 2026-09-29 21:51

from django.db import migrations, models


def migrate_legacy_report_subscriptions(apps, schema_editor):
    Subscription = apps.get_model('sms_campaign_manager', 'ReportSubscription')
    database = schema_editor.connection.alias
    subscriptions = Subscription.objects.using(database)
    through = Subscription.campaigns.through

    for subscription in subscriptions.exclude(campaign_id__isnull=True).iterator():
        through.objects.using(database).get_or_create(
            reportsubscription_id=subscription.pk,
            campaign_id=subscription.campaign_id,
        )

    subscriptions.filter(frequency='daily').update(frequency='1day')
    subscriptions.filter(frequency__in=['weekly', 'monthly', 'on_completion']).update(
        frequency='manual',
        next_run_at=None,
    )
    subscriptions.filter(format='pdf').update(format='html')

    for subscription in subscriptions.filter(name='').iterator():
        Subscription.objects.using(database).filter(pk=subscription.pk).update(
            name=f'Report subscription {subscription.pk}',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaign_manager', '0026_alter_reportdeliverylog_format_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_report_subscriptions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reportsubscription',
            name='frequency',
            field=models.CharField(choices=[('10min', 'Every 10 minutes'), ('1hr', 'Every hour'), ('1day', 'Every day'), ('manual', 'Manual only')], default='manual', max_length=20),
        ),
    ]
